routes/web.php
<?php
URL::forceScheme('https');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Wizard
Route::get('install', 'Expert\WizardController@install')->name('install');
Route::post('db-connection', 'Expert\WizardController@dbConnection')->name('dbConnection');
Route::post('wizard-action', 'Expert\WizardController@wizardAction')->name('wizardAction');

//Work-Start
Route::group(['middleware'=>'dbWizard'], function () {

    Route::get('login', 'Expert\HomeController@login')->name('login');
    Route::post('login', 'Expert\HomeController@loginAction')->name('login');
    Route::get('logout', 'Expert\HomeController@logout')->name('logout');

    Route::group(['middleware'=>'userAuth'], function () {
    Route::get('/', 'Expert\HomeController@app')->name('home');

    	//Admin
    	Route::group(['as'=>'Admin.', 'prefix'=>'admin', 'namespace'=>'Admin'], function () {
        	Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
        	Route::resource('userrole', 'UserroleController');
        	Route::resource('usermanage', 'UserController');
        	Route::get('systemlogs', 'HomeController@systemlogs')->name('systemlogs');
        	Route::get('settings', 'HomeController@settings')->name('settings');
        	Route::post('settingsupdate', 'HomeController@settingsupdate')->name('settingsupdate');

            Route::get('currency', 'HomeController@currency')->name('currency');
            Route::get('showcursymbol', 'HomeController@showcursymbol')->name('showcursymbol');
            Route::get('showcurtext', 'HomeController@showcurtext')->name('showcurtext');
            Route::post('currencyupdate', 'HomeController@currencyupdate')->name('currencyupdate');
                
                
            Route::get('profileupdate', 'UpdateUserController@profileupdate')->name('profileupdate');
            Route::post('updateuser', 'UpdateUserController@updateuser')->name('updateuser');

            Route::get('changepassword', 'UpdateUserController@changepassword')->name('changepassword');
            Route::post('updateuserpass', 'UpdateUserController@updateuserpass')->name('updateuserpass');

            

        // Backup routes
            Route::get('backup', 'BackupController@index');
            Route::get('backup/create', 'BackupController@create');
            Route::get('backup/backup-download/{file_name}', 'BackupController@download');
            Route::get('backup/delete/{file_name}', 'BackupController@delete');
            


            Route::get('bedmanage', 'BedController@bedmanage')->name('bedmanage');
            Route::get('bedadd', 'BedController@bedadd')->name('bedadd');
            Route::post('bedaddac', 'BedController@bedaddac')->name('bedaddac');
            Route::get('beddelete/{id}', 'BedController@beddelete')->name('beddelete');

            Route::get('hospitalcharge', 'HospitalChargeController@hospitalcharge')->name('hospitalcharge');
            Route::get('hospitalchargeadd', 'HospitalChargeController@hospitalchargeadd')->name('hospitalchargeadd');
            Route::post('hospitalchargeac', 'HospitalChargeController@hospitalchargeac')->name('hospitalchargeac');
            Route::get('hospitalchargedelete/{id}', 'HospitalChargeController@hospitalchargedelete')->name('hospitalchargedelete');

            
            Route::get('investigations', 'InvestigationController@investigations')->name('investigations');
            Route::get('investigationsadd', 'InvestigationController@investigationsadd')->name('investigationsadd');
            Route::post('investigationsac', 'InvestigationController@investigationsac')->name('investigationsac');
            Route::get('investigationsdelete/{id}', 'InvestigationController@investigationsdelete')->name('investigationsdelete');
            
            Route::get('invedit/{id}', 'InvestigationController@invedit')->name('invedit');
            Route::post('inveditac/{id}', 'InvestigationController@inveditac')->name('inveditac');

            Route::get('doctors', 'DoctorsController@doctors')->name('doctors');
            Route::get('doctorsadd', 'DoctorsController@doctorsadd')->name('doctorsadd');
            Route::post('doctorsaddac', 'DoctorsController@doctorsaddac')->name('doctorsaddac');
            Route::get('doctorsdelete/{id}', 'DoctorsController@doctorsdelete')->name('doctorsdelete');
            
            
            Route::get('refmanage', 'RefController@refmanage')->name('refmanage');
            Route::get('refadd', 'RefController@refadd')->name('refadd');
            Route::post('refaddac', 'RefController@refaddac')->name('refaddac');
            Route::get('refdelete/{id}', 'RefController@refdelete')->name('refdelete');
            
            Route::get('opd', 'PatientsController@opd')->name('opd');
            Route::get('ipd', 'PatientsController@ipd')->name('ipd');

            Route::get('patients', 'PatientsController@patients')->name('patients');
            Route::get('patientsadd', 'PatientsController@patientsadd')->name('patientsadd');
            Route::post('patientsaddac', 'PatientsController@patientsaddac')->name('patientsaddac');
            Route::get('patientsdelete/{id}', 'PatientsController@patientsdelete')->name('patientsdelete');

            Route::get('bill', 'BillController@bill')->name('bill');
            Route::get('billadd', 'BillController@billadd')->name('billadd');
            Route::get('charge_show', 'BillController@charge_show')->name('charge_show');
            Route::get('investigation_show', 'BillController@investigation_show')->name('investigation_show');
            Route::get('add_item_to_cart', 'BillController@add_item_to_cart')->name('add_item_to_cart');
            Route::get('delete_from_cart', 'BillController@delete_from_cart')->name('delete_from_cart');
            Route::get('calculate_total', 'BillController@calculate_total')->name('calculate_total');

            
            Route::get('hc_rf_calculate_total', 'BillController@hc_rf_calculate_total')->name('hc_rf_calculate_total');

            Route::post('billaction', 'BillController@billaction')->name('billaction');
            Route::get('billprint/{id}', 'BillController@billprint')->name('billprint');
            
            Route::get('billpayment/{id}', 'BillController@billpayment')->name('billpayment');
            Route::post('billpaymentaction/{id}', 'BillController@billpaymentaction')->name('billpaymentaction');
            
            //Pharmacy 

            Route::get('phaproductcategory', 'PharmacyConroller@phaproductcategory')->name('phaproductcategory');
            Route::post('phaproductcategoryadd', 'PharmacyConroller@phaproductcategoryadd')->name('phaproductcategoryadd');

            
            Route::get('pharcatedit/{id}', 'PharmacyConroller@pharcatedit')->name('pharcatedit');
            Route::post('phaproductcategoryeditac/{id}', 'PharmacyConroller@phaproductcategoryeditac')->name('phaproductcategoryeditac');
            

            Route::get('pharcatdel/{id}', 'PharmacyConroller@pharcatdel')->name('pharcatdel');

            Route::get('phamedicinecompany', 'PharmacyConroller@phamedicinecompany')->name('phamedicinecompany');
            Route::post('phamedicinecompanyadd', 'PharmacyConroller@phamedicinecompanyadd')->name('phamedicinecompanyadd');
            Route::get('phamedicinecompanydelete/{id}', 'PharmacyConroller@phamedicinecompanydelete')->name('phamedicinecompanydelete');

            
            Route::get('phamedpurlist', 'PharmacyConroller@phamedpurlist')->name('phamedpurlist');
            Route::get('phamedpur', 'PharmacyConroller@phamedpur')->name('phamedpur');
            Route::get('pha_pur_med_add_item_to_cart', 'PharmacyConroller@pha_pur_med_add_item_to_cart')->name('pha_pur_med_add_item_to_cart');
            Route::get('pha_pur_med_delete_from_cart', 'PharmacyConroller@pha_pur_med_delete_from_cart')->name('pha_pur_med_delete_from_cart');
            Route::post('phamedpuraction', 'PharmacyConroller@phamedpuraction')->name('phamedpuraction');
            Route::get('phamedpurbill/{id}', 'PharmacyConroller@phamedpurbill')->name('phamedpurbill');

            
            Route::get('phamedpurbilledit/{id}', 'PharmacyConroller@phamedpurbilledit')->name('phamedpurbilledit');
            Route::post('phamedpureditac/{id}', 'PharmacyConroller@phamedpureditac')->name('phamedpureditac');
            
            
            Route::get('phamedselllist', 'PharmacyConroller@phamedselllist')->name('phamedselllist');
            Route::get('phamedsell', 'PharmacyConroller@phamedsell')->name('phamedsell');

            
            Route::get('medicinesellshow', 'PharmacyConroller@medicinesellshow')->name('medicinesellshow');
            
            Route::get('med_sales_add_item_to_cart', 'PharmacyConroller@med_sales_add_item_to_cart')->name('med_sales_add_item_to_cart');
            Route::get('med_sales_delete_from_cart', 'PharmacyConroller@med_sales_delete_from_cart')->name('med_sales_delete_from_cart');
            
            
            Route::post('phamedsalesaction', 'PharmacyConroller@phamedsalesaction')->name('phamedsalesaction');
            Route::get('phamedsalesbill/{pat_id}', 'PharmacyConroller@phamedsalesbill')->name('phamedsalesbill');



            Route::get('medicinereturn', 'PharmacyConroller@medicinereturn')->name('medicinereturn');
            Route::post('medicinereturnbillview', 'PharmacyConroller@medicinereturnbillview')->name('medicinereturnbillview');
            Route::get('phamedreturnbill/{id}', 'PharmacyConroller@phamedreturnbill')->name('phamedreturnbill');
            
            //alamin start

resources/views/admin/pharmacysell/medicinereturn.blade.php
@extends('expert.master')

@section('title', 'Merchant Payment Report- '.$settingsinfo->company_name.' - '.$settingsinfo->soft_name.'')

@section('content')

@include('expert.sidebar')

@include('expert.topbar')

<style type="text/css">

.table-responsive {
    white-space: normal;
}
.dataTables_length{
  display: none;
}
</style>

<div class="clearfix"></div>
	
  <div class="content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <div class="card bg-dark">
      		<div class="card-header border-0 bg-transparent text-white">
                <i class="fa fa-list"></i><span> Merchant Payment Report </span>
            </div>

            <div class="card">
            <div class="card-header">
              
              <?php if (session('message')): ?>
        <div class="col-lg-12">
            <div class="alert alert-{{session('class')}} alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <div class="alert-icon contrast-alert"><i class="icon-close"></i></div>
              <div class="alert-message"><span>{{session('message')}}</span></div>
            </div>
        </div>
        <?php endif; ?>

              <form action="{{url('admin/medicinereturnbillview')}}" method="post">
              @csrf


              <div class="row">

                <div class="col-md-6">         
                  <div class="form-group" style="margin-bottom: 0rem;">
                    
                    <select type="text" class="form-control" id="bil_id" name="bil_id" required="">
                        <option value="">Select Bill ID</option>
 
                        @foreach($bill_manage as $data)
                          <option value="{{$data->bill_id}}">{{$data->bill_id}} </option>
                        @endforeach

                    </select>
                    
                  </div>
                </div>


                <div class="col-md-6">         
                  <div class="form-group pull-right" style="margin-bottom: 0rem;">
             
                    <button type="submit" class="btn btn-gradient-orange waves-effect waves-light m-1" style="margin-top: 0px !important;">
                      View 
                    </button>
                  </div>
                </div>

              </form>
            </div>
            </div>
          
            
            <div class="card-body">

            
            </div>
          </div>
               
          </div>
        </div>
      </div><!--End Row-->
	  
       <!--End Dashboard Content-->

    </div>
    <!-- End container-fluid-->
    
    </div><!--End content-wrapper-->
   

  @include('expert.copyright')

  @endsection

  @section('js')
    <script>
    $(document).ready(function() {
        dataTableLoad({
            curUrl: "{{route('Admin.usermanage.index')}}",
            //dataUrl: "{{route('Admin.usermanage.index')}}",
            addUrl: "{{route('Admin.usermanage.index')}}"
        });
    });

    $(document).ready(function() {
      $("#bil_id").select2();
    });
    </script>
  @endsection

resources/views/admin/pharmacysell/medicinereturnbypatient.blade.php
@extends('expert.master')

@section('title', 'Merchant Payment Report- '.$settingsinfo->company_name.' - '.$settingsinfo->soft_name.'')

@section('content')

@include('expert.sidebar')

@include('expert.topbar')

<style type="text/css">

.table-responsive {
    white-space: normal;
}
.dataTables_length{
  display: none;
}
</style>

<div class="clearfix"></div>
	
  <div class="content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <div class="card bg-dark">
      		<div class="card-header border-0 bg-transparent text-white">
                <i class="fa fa-list"></i><span> Return Medicine </span>
            </div>

            <div class="card">
            <div class="card-header">
              
              <?php if (session('message')): ?>
        <div class="col-lg-12">
            <div class="alert alert-{{session('class')}} alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <div class="alert-icon contrast-alert"><i class="icon-close"></i></div>
              <div class="alert-message"><span>{{session('message')}}</span></div>
            </div>
        </div>
        <?php endif; ?>

              <form action="{{url('admin/medicinereturnbypatientbillview')}}" method="post">
              @csrf


              <div class="row">

                <div class="col-md-6">         
                  <div class="form-group" style="margin-bottom: 0rem;">
                    
                    <select type="text" class="form-control" id="patient_id" name="patient_id" required="">
                        <option value="">Select Patient ID</option>
 
                        @foreach($patient_info as $data)
                          <option value="{{$data->pat_id}}">{{$data->pat_id}} </option>
                        @endforeach

                    </select>
                    
                  </div>
                </div>


                <div class="col-md-6">         
                  <div class="form-group pull-right" style="margin-bottom: 0rem;">
             
                    <button type="submit" class="btn btn-gradient-orange waves-effect waves-light m-1" style="margin-top: 0px !important;">
                      View 
                    </button>
                  </div>
                </div>

              </form>
            </div>
            </div>
          
            
            <div class="card-body">

            
            </div>
          </div>
               
          </div>
        </div>
      </div><!--End Row-->
	  
       <!--End Dashboard Content-->

    </div>
    <!-- End container-fluid-->
    
    </div><!--End content-wrapper-->
   

  @include('expert.copyright')

  @endsection

  @section('js')
    <script>
    $(document).ready(function() {
        dataTableLoad({
            curUrl: "{{route('Admin.usermanage.index')}}",
            //dataUrl: "{{route('Admin.usermanage.index')}}",
            addUrl: "{{route('Admin.usermanage.index')}}"
        });
    });

    $(document).ready(function() {
      $("#patient_id").select2();
    });
    </script>
  @endsection

resources/views/admin/pharmacysell/phamedsalesbill.blade.php
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
  <meta name="description" content=""/>
  <meta name="author" content=""/>
  <meta name="csrf-token" content="siQAzC5MB0KAaw3OMNuipUFVbuRGJiPjNXzStNzI">
<title> Medicine Purchase Invoice - {{$bill_manage->bill_id}} - {{$settingsinfo->company_name}} </title>
  <!--favicon-->
  <link rel="icon" type="image/png" href="{{ asset('/logo/158116565711.png') }}" />
  
<style>
body{
font-family: 'Linux Libertine','Georgia','Times',serif;
}

.sagor{
  font-size:14px;
  font-family: 'Linux Libertine','Georgia','Times',serif;
  font-weight: bold;
}

@media print {
  
.noprint{
  display: none;
}

/*#sidebar-wrapper,.pb-2,.footer,.no-print {visibility: hidden;}
.content-wrapper,.card-body {margin-left: 0px;}
.content-wrapper {margin-top: 45px;}
html, body {
  background: #fff;
  font-family: sans-serif;
  color: #636363;
  letter-spacing: 1px;
  position: relative;
  margin: 0px auto; 
  font-size: 12px !important;
  width: 300px !important;
}*/

}



</style>

</head>

<body>

<div align="center" class="sagor">
  <table width="300" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <td width="280" height="50" align="center" valign="middle" style="font-size:16px; font-weight:bold;">Modern Hospital Private</td>
    </tr>
    <tr>
      <td height="10">        </td>
    </tr>
    <tr>
      <td>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td height="50" align="center" valign="middle" class="sagor" style="font-size:16px; font-weight:bold;">Medicine Sales Bill </strong></td>
          </tr>
        <tr>
          <td width="50%" height="30" class="sagor">Bill ID : <strong><strong>{{$bill_manage->bill_id}}</strong></td>
          </tr>

<tr>
          <td height="30" class="sagor">Date : <strong>{{$bill_manage->date_time}}</strong></td>
          </tr>

        <tr>
          <td height="30" class="sagor">Patient : <strong>{{$bill_manage->patient}}</strong></td>
          </tr>
    <tr>

      <tr>
          <td height="30" class="sagor">Patient ID : <strong>{{$bill_manage->pat_id}}</strong></td>
          </tr>
    <tr>

<tr>
          <td height="30" class="sagor">Bed : <strong>{{$bill_manage->bed}}</strong></td>
          </tr>
    <tr>

          <td height="30" class="sagor">Status : <strong>{{$bill_manage->status}}</strong></td>
          </tr>
        
<tr>
          <td height="30" class="sagor">Sales User : <strong><strong>{{@$bill_manage->sales_user}}</strong></td>
          </tr>    
      
      
       <tr>
          <td height="30" class="sagor">Total Amount : <strong>{{$bill_manage->in_total}} TK</strong></td>
          </tr>
      </table></td>
    </tr>
    <tr>
       <td height="10" >

              
   <table width="100%" border="0" cellspacing="2" cellpadding="2">
         <tr>
           <td width="5%" height="30" align="center" valign="middle" style="border-top: 1px solid #000;border-bottom: 1px solid #000;" class="sagor"><strong>#</strong></td>
      
           <td width="40%" align="left" valign="middle" style="border-top: 1px solid #000;border-bottom: 1px solid #000;" class="sagor"><strong>Medicine   </strong></td>
       <td width="10%" align="center" valign="middle" style="border-top: 1px solid #000;border-bottom: 1px solid #000;" class="sagor"><strong>QTY</strong></td>
          
           <td width="15%" align="center" valign="middle" style="border-top: 1px solid #000;border-bottom: 1px solid #000;" class="sagor"><strong> Price</strong></td>
            <td width="15%" align="center" valign="middle" style="border-top: 1px solid #000;border-bottom: 1px solid #000;" class="sagor"><strong> Total</strong></td>
          </tr>
          @php
            $i=1;

          @endphp

          @foreach($pha_sales_add_to_cart as $data)
         <tr>
           <td height="30" align="center" valign="middle" style="border-bottom: 1px solid #000;" class="sagor">
            {{$i++}}           </td>
           <td align="left" valign="middle" style="border-bottom: 1px solid #000;" class="sagor">{{$data->med_name}} </td>
           <td align="center" valign="middle" style="border-bottom: 1px solid #000;" class="sagor">{{$data->qty}} </td>
           <td align="center" valign="middle" style="border-bottom: 1px solid #000;" class="sagor">{{$data->price}} </td>
           <td align="center" valign="middle" style="border-bottom: 1px solid #000;" class="sagor">{{$data->total}} </td>
          </tr>
          @endforeach
          <tr>
           <td height="30" align="center" valign="middle" colspan="3">&nbsp;</td>
           <td align="right" valign="middle" class="sagor">
             <strong> Sub Total : </strong>           </td>
           <td align="center" valign="middle" style="border-bottom: 1px solid #000;" class="sagor"><strong> {{$bill_manage->total}}  TK </strong></td>
     
          </tr>
          <tr>
           <td height="30" align="center" valign="middle" colspan="3">&nbsp;</td>
           <td align="right" valign="middle" class="sagor">
             <strong> Discount : </strong>           </td>
           <td align="center" valign="middle" style="border-bottom: 1px solid #000;" class="sagor"><strong> {{$bill_manage->discount}}  TK </strong></td>
     
          </tr>
          <tr>
           <td height="30" align="center" valign="middle" colspan="3">&nbsp;</td>
           <td align="right" valign="middle" class="sagor">
             <strong> Total : </strong>           </td>
           <td align="center" valign="middle" style="border-bottom: 1px solid #000;" class="sagor"><strong> {{$bill_manage->in_total}}  TK </strong></td>
     
          </tr>
       </table>     </td>
    </tr>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr >
      <td height="50">&nbsp;</td>
    </tr>
  <tr class="noprint">
      <td height="50">

        <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td align="center" valign="middle">
            <a href="{{url('admin/phamedselllist')}}" style="background: #db5246; border: 1px solid #db5246; padding:15px; color: #ffffff; text-decoration: none; ">
                <i class="fa fa-check-square-o"></i> Back            </a>          </td>
          <td align="center" valign="middle">&nbsp;</td>
          <td align="center" valign="middle">
            <button onClick="window.print()" style="background: #129a5a; border: 1px solid #129a5a; padding:15px; color: #ffffff; text-decoration: none;cursor: pointer;font-size: 18px;">
                <i class="fa fa-check-square-o"></i> Print            </button>          </td>
        </tr>
      </table>    </td>
    </tr>
  </table>
</div>


</body>
</html>

resources/views/admin/pharmacysell/phamedselllist.blade.php
@extends('expert.master')

@section('title', 'Medicine Sell List Phaymacy - '.$settingsinfo->company_name.' - '.$settingsinfo->soft_name.'')

@section('content')

@include('expert.sidebar')

@include('expert.topbar')

<div class="clearfix"></div>
	
  <div class="content-wrapper">
    <div class="container-fluid">
      <div class="row">

        <?php if (session('message')): ?>
          <div class="col-lg-12">
              <div class="alert alert-{{session('class')}} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <div class="alert-icon contrast-alert"><i class="icon-close"></i></div>
                <div class="alert-message"><span>{{session('message')}}</span></div>
              </div>
            </div>
        <?php endif; ?>

        <div class="col-lg-12">

      

          <div class="card bg-dark">
      		<div class="card-header border-0 bg-transparent text-white">
                <i class="fa fa-user-circle"></i><span>Medicine Sell List Manage</span>
            </div>

            <div class="card">
            <div class="card-header">

              <div style="display:inline-block; padding-top:5px;">
                <i class="fa fa-table"></i> Medicine Sell List
              </div> 

             

            </div>
            <div class="card-body">
              <div class="table-responsive">
              <table id="dataTable" class="table table-bordered">
                <thead>
                    <tr>
                        <th width="5%">SN</th>
                        <th>Bill ID </th>
                        <th>Date </th>
                        <th>Patient</th>
                        <th>Total</th>
                        <th>Discount </th>
                        <th>In Total </th>
                        <th>Status </th>
                        <th width="8%" class="text-center">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @php $i=1; @endphp
                    @foreach($pha_sales_manage as $data)
                    <tr>
                        <td>{{$i++}}</td>
                        <td>{{$data->bill_id}}</td>
                        <td>{{$data->date}}</td>
                        <td>{{$data->patient}}</td>
                        <td>{{$data->total}}</td>
                        <td>{{$data->discount}}</td>
                        <td>{{$data->in_total}}</td>
                        <td>{{$data->status}}</td>
                        <td>

                          <a href="{{url('admin/phamedsalesbill',$data->bill_id)}}" class="btn btn-warning btn-sm waves-effect waves-light"> 
                            <i class="fa fa-print"></i> <span> Print Bill</span>
                          </a>

                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            </div>
            </div>
          </div>
               
          </div>
        </div>



        



      </div><!--End Row-->
	  
       <!--End Dashboard Content-->

    </div>
    <!-- End container-fluid-->
    
    </div><!--End content-wrapper-->
   

  @include('expert.copyright')

  @endsection

  @section('js')
    <script>
    $(document).ready(function() {
        dataTableLoad({
            curUrl: "{{route('Admin.userrole.index')}}",
            addUrl: "{{route('Admin.userrole.create')}}"
        });
    });
    </script>
  @endsection