routes/web.php
<?php
URL::forceScheme('https');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Wizard
Route::get('install', 'Expert\WizardController@install')->name('install');
Route::post('db-connection', 'Expert\WizardController@dbConnection')->name('dbConnection');
Route::post('wizard-action', 'Expert\WizardController@wizardAction')->name('wizardAction');

//Work-Start
Route::group(['middleware'=>'dbWizard'], function () {

    Route::get('login', 'Expert\HomeController@login')->name('login');
    Route::post('login', 'Expert\HomeController@loginAction')->name('login');
    Route::get('logout', 'Expert\HomeController@logout')->name('logout');

    Route::group(['middleware'=>'userAuth'], function () {
    Route::get('/', 'Expert\HomeController@app')->name('home');

    	//Admin
    	Route::group(['as'=>'Admin.', 'prefix'=>'admin', 'namespace'=>'Admin'], function () {
        	Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
        	Route::resource('userrole', 'UserroleController');
        	Route::resource('usermanage', 'UserController');
        	Route::get('systemlogs', 'HomeController@systemlogs')->name('systemlogs');
        	Route::get('settings', 'HomeController@settings')->name('settings');
        	Route::post('settingsupdate', 'HomeController@settingsupdate')->name('settingsupdate');

            Route::get('currency', 'HomeController@currency')->name('currency');
            Route::get('showcursymbol', 'HomeController@showcursymbol')->name('showcursymbol');
            Route::get('showcurtext', 'HomeController@showcurtext')->name('showcurtext');
            Route::post('currencyupdate', 'HomeController@currencyupdate')->name('currencyupdate');
                
                
            Route::get('profileupdate', 'UpdateUserController@profileupdate')->name('profileupdate');
            Route::post('updateuser', 'UpdateUserController@updateuser')->name('updateuser');

            Route::get('changepassword', 'UpdateUserController@changepassword')->name('changepassword');
            Route::post('updateuserpass', 'UpdateUserController@updateuserpass')->name('updateuserpass');

            

        // Backup routes
            Route::get('backup', 'BackupController@index');
            Route::get('backup/create', 'BackupController@create');
            Route::get('backup/backup-download/{file_name}', 'BackupController@download');
            Route::get('backup/delete/{file_name}', 'BackupController@delete');
            


            Route::get('bedmanage', 'BedController@bedmanage')->name('bedmanage');
            Route::get('bedadd', 'BedController@bedadd')->name('bedadd');
            Route::post('bedaddac', 'BedController@bedaddac')->name('bedaddac');
            Route::get('beddelete/{id}', 'BedController@beddelete')->name('beddelete');

            Route::get('hospitalcharge', 'HospitalChargeController@hospitalcharge')->name('hospitalcharge');
            Route::get('hospitalchargeadd', 'HospitalChargeController@hospitalchargeadd')->name('hospitalchargeadd');
            Route::post('hospitalchargeac', 'HospitalChargeController@hospitalchargeac')->name('hospitalchargeac');
            Route::get('hospitalchargedelete/{id}', 'HospitalChargeController@hospitalchargedelete')->name('hospitalchargedelete');

            
            Route::get('investigations', 'InvestigationController@investigations')->name('investigations');
            Route::get('investigationsadd', 'InvestigationController@investigationsadd')->name('investigationsadd');
            Route::post('investigationsac', 'InvestigationController@investigationsac')->name('investigationsac');
            Route::get('investigationsdelete/{id}', 'InvestigationController@investigationsdelete')->name('investigationsdelete');
            
            Route::get('invedit/{id}', 'InvestigationController@invedit')->name('invedit');
            Route::post('inveditac/{id}', 'InvestigationController@inveditac')->name('inveditac');

            Route::get('doctors', 'DoctorsController@doctors')->name('doctors');
            Route::get('doctorsadd', 'DoctorsController@doctorsadd')->name('doctorsadd');
            Route::post('doctorsaddac', 'DoctorsController@doctorsaddac')->name('doctorsaddac');
            Route::get('doctorsdelete/{id}', 'DoctorsController@doctorsdelete')->name('doctorsdelete');
            
            
            Route::get('refmanage', 'RefController@refmanage')->name('refmanage');
            Route::get('refadd', 'RefController@refadd')->name('refadd');
            Route::post('refaddac', 'RefController@refaddac')->name('refaddac');
            Route::get('refdelete/{id}', 'RefController@refdelete')->name('refdelete');
            
            Route::get('opd', 'PatientsController@opd')->name('opd');
            Route::get('ipd', 'PatientsController@ipd')->name('ipd');

            Route::get('patients', 'PatientsController@patients')->name('patients');
            Route::get('patientsadd', 'PatientsController@patientsadd')->name('patientsadd');
            Route::post('patientsaddac', 'PatientsController@patientsaddac')->name('patientsaddac');
            Route::get('patientsdelete/{id}', 'PatientsController@patientsdelete')->name('patientsdelete');

            Route::get('bill', 'BillController@bill')->name('bill');
            Route::get('billadd', 'BillController@billadd')->name('billadd');
            Route::get('charge_show', 'BillController@charge_show')->name('charge_show');
            Route::get('investigation_show', 'BillController@investigation_show')->name('investigation_show');
            Route::get('add_item_to_cart', 'BillController@add_item_to_cart')->name('add_item_to_cart');
            Route::get('delete_from_cart', 'BillController@delete_from_cart')->name('delete_from_cart');
            Route::get('calculate_total', 'BillController@calculate_total')->name('calculate_total');

            
            Route::get('hc_rf_calculate_total', 'BillController@hc_rf_calculate_total')->name('hc_rf_calculate_total');

            Route::post('billaction', 'BillController@billaction')->name('billaction');
            Route::get('billprint/{id}', 'BillController@billprint')->name('billprint');
            
            Route::get('billpayment/{id}', 'BillController@billpayment')->name('billpayment');
            Route::post('billpaymentaction/{id}', 'BillController@billpaymentaction')->name('billpaymentaction');
            
            //Pharmacy 

            Route::get('phaproductcategory', 'PharmacyConroller@phaproductcategory')->name('phaproductcategory');
            Route::post('phaproductcategoryadd', 'PharmacyConroller@phaproductcategoryadd')->name('phaproductcategoryadd');

            
            Route::get('pharcatedit/{id}', 'PharmacyConroller@pharcatedit')->name('pharcatedit');
            Route::post('phaproductcategoryeditac/{id}', 'PharmacyConroller@phaproductcategoryeditac')->name('phaproductcategoryeditac');
            

            Route::get('pharcatdel/{id}', 'PharmacyConroller@pharcatdel')->name('pharcatdel');

            Route::get('phamedicinecompany', 'PharmacyConroller@phamedicinecompany')->name('phamedicinecompany');
            Route::post('phamedicinecompanyadd', 'PharmacyConroller@phamedicinecompanyadd')->name('phamedicinecompanyadd');
            Route::get('phamedicinecompanydelete/{id}', 'PharmacyConroller@phamedicinecompanydelete')->name('phamedicinecompanydelete');

            
            Route::get('phamedpurlist', 'PharmacyConroller@phamedpurlist')->name('phamedpurlist');
            Route::get('phamedpur', 'PharmacyConroller@phamedpur')->name('phamedpur');
            Route::get('pha_pur_med_add_item_to_cart', 'PharmacyConroller@pha_pur_med_add_item_to_cart')->name('pha_pur_med_add_item_to_cart');
            Route::get('pha_pur_med_delete_from_cart', 'PharmacyConroller@pha_pur_med_delete_from_cart')->name('pha_pur_med_delete_from_cart');
            Route::post('phamedpuraction', 'PharmacyConroller@phamedpuraction')->name('phamedpuraction');
            Route::get('phamedpurbill/{id}', 'PharmacyConroller@phamedpurbill')->name('phamedpurbill');

            
            Route::get('phamedpurbilledit/{id}', 'PharmacyConroller@phamedpurbilledit')->name('phamedpurbilledit');
            Route::post('phamedpureditac/{id}', 'PharmacyConroller@phamedpureditac')->name('phamedpureditac');
            
            
            Route::get('phamedselllist', 'PharmacyConroller@phamedselllist')->name('phamedselllist');
            Route::get('phamedsell', 'PharmacyConroller@phamedsell')->name('phamedsell');

            
            Route::get('medicinesellshow', 'PharmacyConroller@medicinesellshow')->name('medicinesellshow');
            
            Route::get('med_sales_add_item_to_cart', 'PharmacyConroller@med_sales_add_item_to_cart')->name('med_sales_add_item_to_cart');
            Route::get('med_sales_delete_from_cart', 'PharmacyConroller@med_sales_delete_from_cart')->name('med_sales_delete_from_cart');
            
            
            Route::post('phamedsalesaction', 'PharmacyConroller@phamedsalesaction')->name('phamedsalesaction');
            Route::get('phamedsalesbill/{pat_id}', 'PharmacyConroller@phamedsalesbill')->name('phamedsalesbill');



            Route::get('medicinereturn', 'PharmacyConroller@medicinereturn')->name('medicinereturn');
            Route::post('medicinereturnbillview', 'PharmacyConroller@medicinereturnbillview')->name('medicinereturnbillview');
            Route::get('phamedreturnbill/{id}', 'PharmacyConroller@phamedreturnbill')->name('phamedreturnbill');
            
            //alamin start

app/Http/Controllers/Admin/UserroleController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Userrole;
use App\Model\Logs;
use Auth;

class UserroleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data["datalist"] = Userrole::orderBy('id', 'desc')
            ->get();
        return view('admin.userrole.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.userrole.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $this->validate($request, [
            'role_name' => 'required',
        ]);

        $inputData = [
            'role_name' => $request->role_name
        ];
        
        Userrole::create($inputData);

        Logs::add("User Role Manage", "add", $inputData);

        echo json_encode([
            "status"=>"success",
            "message"=>"User Role has created successfully"
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data["data"] = Userrole::find($id);
        return view('admin.userrole.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validated = $this->validate($request, [
            'role_name' => 'required'
        ]);

        $data = [
            'role_name' => $request->role_name
        ];

        Logs::add("User Role Manage", "edit", $data);

        Userrole::find($id)->update($data);

        echo json_encode([
            "status"=>"success",
            "message"=>"User Role has updated successfully"
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Userrole::find($id)->toArray();

        Logs::add("User Role Manage", "delete", $data);

        Userrole::find($id)->delete();
        echo json_encode([
            "status"=>"success",
            "message"=>"User Role has updated successfully"
        ]);
    }
}

resources/views/admin/userrole/create.blade.php
<form action="{{route('Admin.userrole.store')}}" method="post">
    @csrf
    <div class="modal-header bg-dark">
        <h5 class="modal-title text-white"><i class="fa fa-plus"></i> New Add</h5>
        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <div class="modal-body">
        <div id="validate-error"></div>
        <div class="row">
            
            <div class="col-md-12">
                <div class="form-group">
                    <label for="status">Designation </label>
                    <input required="" type="text" class="form-control" id="role_name" name="role_name" placeholder="Enter Role Name">
                </div>
            </div>

        </div>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-inverse-dark" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
        <button type="submit" class="btn btn-dark"><i class="fa fa-check-square-o"></i> Save</button>
    </div>
</form>

resources/views/admin/userrole/edit.blade.php
<form action="{{route('Admin.userrole.update', $data->id)}}" method="put">
    @csrf
    <div class="modal-header bg-dark">
        <h5 class="modal-title text-white"><i class="fa fa-edit"></i> Update</h5>
        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <div class="modal-body">
        <div id="validate-error"></div>
        <div class="row">
            
            <div class="col-md-12">
                <div class="form-group">
                    <label for="username">Designation </label>
                    <input required="" type="text" class="form-control" id="role_name" name="role_name" placeholder="Enter Role Name" value="{{$data->role_name}}">
                </div>
            </div>
            
            
        </div>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-inverse-dark" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
        <button type="submit" class="btn btn-dark"><i class="fa fa-check-square-o"></i> Save</button>
    </div>
</form>

resources/views/admin/userrole/index.blade.php
@extends('expert.master')

@section('title', 'Designation - '.$settingsinfo->company_name.' - '.$settingsinfo->soft_name.'')

@section('content')

@include('expert.sidebar')

@include('expert.topbar')

<div class="clearfix"></div>
	
  <div class="content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <div class="card bg-dark">
      		<div class="card-header border-0 bg-transparent text-white">
                <i class="fa fa-user-circle"></i><span> Designation Manage</span>
            </div>

            <div class="card">
            <div class="card-header"><div style="display:inline-block; padding-top:5px;"><i class="fa fa-table"></i> Designation List</div> <button type="button" class="btn btn-dark btn-sm waves-effect waves-light pull-right" id="addNew"> <i class="fa fa-plus"></i> <span>Add New</span></button></div>
            <div class="card-body">
              <div class="table-responsive">
              <table id="dataTable" class="table table-bordered">
                <thead>
                    <tr>
                        <th width="5%">SN</th>
                        <th>Designation</th>
                        <th width="8%" class="text-center">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @php $i=1; @endphp
                    @foreach($datalist as $datalist)
                    <tr>
                        <td>{{$i++}}</td>
                        <td>{{$datalist->role_name}}</td>
                        <td><button type="button" class="btn btn-warning btn-sm waves-effect waves-light edit" data="{{$datalist->id}}"> <i class="fa fa-edit"></i> <span>Edit</span></button> <button type="button" class="btn btn-danger btn-sm waves-effect waves-light delete" data="{{$datalist->id}}"> <i class="fa fa-times"></i> <span>Delete</span></button></td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            </div>
            </div>
          </div>
               
          </div>
        </div>
      </div><!--End Row-->
	  
       <!--End Dashboard Content-->

    </div>
    <!-- End container-fluid-->
    
    </div><!--End content-wrapper-->
   

  @include('expert.copyright')

  @endsection

  @section('js')
    <script>
    $(document).ready(function() {
        dataTableLoad({
            curUrl: "{{route('Admin.userrole.index')}}",
            addUrl: "{{route('Admin.userrole.create')}}"
        });
    });
    </script>
  @endsection